services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./next.config.mjs
          action: rebuild
        - path: .
          target: /app
          action: sync
    env_file:
      - .env.local
    depends_on:
      - db

  db:
    image: postgres:15.4
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
