services:
  web:
    image: ghcr.io/romoguill/farm-contracts:latest
    ports:
      - 3001:3000
    env_file:
      - .env.production.local
    restart: unless-stopped
    networks:
      - internal_net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15.4
    ports:
      - 5432:5432
    env_file:
      - .env.production.local
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal_net
    volumes:
      - db-prod:/var/lib/postgresql/data

networks:
  internal_net:
    name: internal_net

volumes:
  db-prod:
