name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub checkout
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build image
        run: |
          docker buildx build -f Dockerfile -t ghcr.io/romoguill/farm-contracts
          docker push ghcr.io/romoguill/farm-contracts:latest
