name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build image
        run: |
          docker buildx build -f Dockerfile -t ghcr.io/romoguill/farm-contracts .
          docker push ghcr.io/romoguill/farm-contracts:latest

  deploy:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/apps/farm-contracts
            docker login ghcr.io -u romoguill -p ${{ secrets.REGISTRY_TOKEN }}
            docker pull ghcr.io/romoguill/farm-contracts:latest
            docker compose -f docker-compose.prod.yml --env-file=.env.local up -d
