name: Docker Image CI

on:
  push:
    branches: ['main']

env:
  NEXT_IMAGE_NAME: farm-contracts-nextjs
  PROJECT_NAME: farm-contracts

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build image
        run: |
          docker buildx build -f Dockerfile.prod -t ghcr.io/${{ github.actor }}/$NEXT_IMAGE_NAME .
          docker push ghcr.io/${{ github.actor }}/$NEXT_IMAGE_NAME:latest

      - name: Copy docker-compose configuration to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'docker-compose.prod.yml'
          target: /home/${{ github.actor }}/apps/$NEXT_IMAGE_NAME

  deploy:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/apps/$PROJECT_NAME
            echo "${{ secrets.ENV_VARS }}" > .env.production.local
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.REGISTRY_TOKEN }}
            docker pull ghcr.io/${{ github.actor }}/$NEXT_IMAGE_NAME:latest
            docker compose -f docker-compose.prod.yml up -d
